# main config file

# table of tables
[subvolume]
path = "/path/to/subvolume"

# default config for a single subvolume
keep-hourly = 5
keep-daily = 10
keep-weekly = 0
keep-monthly = 10
keep-yearly = 10

[subvolume.snapshots."subvolume-2019-01-27T23:04:35.418948"]
path = "/path/to/subvolume/.snapshots/subvolume-2019-01-27T23:04:35.418948"
creation-date-time = "2019-01-27T23:04:35.418948"
type = "init"

# [configs.default.snapshots.snapshot]
# list of snapshots
# name = ""
# type = "" # daily or hourly
# path = ""
# creation_date_time = "" # iso format
